### ISSUE TITLE
License label

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/ContainerApplicationGenericLabels#2]
Can the image have a license? I feel like this is pretty problematic when most images are composed of multiple pieces of various software with different licenses.

**Comment by rhatdan** [comment]
I would guess the layer could have a license.  These labels are not required.  I would say think of these more as applications then container images.  I as a third party ACME could add a flag saying that this software requires an ACME License to run

**Comment by llunved** [comment]
I think that most if not all images will end up with "MULTIPLE" as the license. In any case we should clarify that the 'License' label refers to the content not the image as an aggregate work - which I think would not constitute enough of creative work to even be protected.

**Comment by rhatdan** [comment]
Send me a patch with the wording you would like, or to pull the term.  I am not wedded to it one way or another.

**Comment by ghost** [comment]
Well, I think we should remove the license label as it will be confusing in most cases: either it will be multiple, or it will be set inaccurately....

**Comment by rhatdan** [comment]
Ok lets remove it.

**Comment by rhatdan** [comment]
Removed

**Comment by richardfontana** [comment]
When this came up last year I agreed with @riekrh. Recently though I've been thinking that the absence of any standard kind of license metadata for Docker images is suboptimal. Maybe this should be reconsidered?

**Comment by llunved** [comment]
Is there perhaps a better way to define a standard for referencing a document on the licenses for the content included in the image, rather than a single metadata field trying to summarize all of them?
