### ISSUE TITLE
Define standard for vendor-specific Labels

### ISSUE THREAD

**Issue by ghost** [projectatomic/ContainerApplicationGenericLabels#34]
Based on some of the discussions on this proposal and subsequent pull requests, there appear to be some use cases for labels that are too specific to try to standardize (e.g. this came up in the authoritative_source and distribution_scope context). 

We should define a standard for naming vendor-specific labels.

**Comment by philips** [comment]
In appc we namespace by domains. So rpm.org/foobar or something.

**Comment by goern** [comment]
and dont we have https://docs.docker.com/userguide/labels-custom-metadata/ for that?

**Comment by ghost** [comment]
I am not opposed to follow the docker proposal, however they are using dots (".") while we agreed to use underscore ("_") as a separator.

**Comment by rhatdan** [comment]
Well . separation could be for domain, and then _ separation be for primary label.

redhat.com/satellite_server_config

@philips It is doing by domain, not reverse domain?

com.redhat  versus redhat.com

**Comment by ghost** [comment]
I would vote for reverse domain as that makes sorting look more reasonable to me.

Do you want to do dot-slash-underscore or follow the Docker precedent of dot and then just use the underscore in the field name?

E.g.: "com.redhat/build_host" vs. "com.redhat.build_host"

**Comment by rhatdan** [comment]
I have no preference, I think we follow the Open Container Standard, @philips ???

**Comment by Zyzyx** [comment]
No preference for me either. I like the former (with a slash) just for aesthetics, but eh, not a strong preference.

**Comment by rhatdan** [comment]
So / is agreed upon, now it is whether or not to use domain or reverse domain format.  @philips Comment?

**Comment by philips** [comment]
Open Container Standard has not addressed anything beyond host local so labels haven't come up, yet.

**Comment by ghost** [comment]
So based on the docker precedence and the use by OpenShift today, we will do a PR with "com.redhat.build_host".
