### ISSUE TITLE
A label for changelog

### ISSUE THREAD

**Issue by rwngwn** [projectatomic/ContainerApplicationGenericLabels#38]
Hi, 
I'm now working on a way how to put changelog information to OpenShift Xpaas JBoss MW images and I'd like to see some more standard way to attach some release notes/changelog to an image even for regular container application.    

Ideally it should be two labels like:

| Name | Description |
| --- | --- |
| changelog | a brief release notes/description whats new in image |
| changelog_url | url to a webpage containing description of all new shiny stuff |

**Comment by goldmann** [comment]
I do not necessarily like the `changelog_url` label. IMHO it would be better to have only `changelog`, where the content could be one of:
1. Short description of the change (image respin is one example), or
2. Link to release notes.

**Comment by vpavlin** [comment]
I'd suggest adding just `changelog` which would strictly contain a link to release notes. I envision labels more as machine-readable information and thus pasting arbitrary text doesn't make much sense to me.

**Comment by goldmann** [comment]
Sure, I'm cool with this. Should we send a PR for this?

**Comment by rhatdan** [comment]
I would prefer to update this pull request if that is the consensus.

**Comment by goldmann** [comment]
There is no PR submitted to fix this issue, yet. I'll prepare one.

**Comment by jmtd** [comment]
This looks good to me. I hope we can get this into the next release of xPaas images.
