### ISSUE TITLE
Use dash case instead of underscore in label names

### ISSUE THREAD

**Issue by mfojtik** [projectatomic/ContainerApplicationGenericLabels#47]
Are there any reasons why the labels are `authoritative_source` and not `authoritative-source` ? Kubernetes and OpenShift labels seems to both follow the `foo-bar` case. Also the Docker upstream promote the "dash" case: https://docs.docker.com/userguide/labels-custom-metadata/

**Comment by mfojtik** [comment]
@aweiteka ?

**Comment by soltysh** [comment]
:+1: we've applied exactly the same patterns in s2i as well. Atomic should not be different in this, imho.

**Comment by aweiteka** [comment]
It sounds like we've diverged in our convention, highlighting the need for these standards so we can programatically use these things in automation. This repo has several underscore "_" keys specified and we have followed that in our base images. I'm not sure how to decide between the two but the upstream docker convention does tip in favor of dash "-". I doubt there's much automation relying on these keys yet.

Any other stakeholders want to weigh in?

**Comment by ncdc** [comment]
+1000 to dash

**Comment by TomasTomecek** [comment]
We don't care much (dash looks nicer though). If you make a change, do it sooner rather than later please. We would prefer not change  labels every week.

**Comment by rhatdan** [comment]
@riekrh @philips PTAL

**Comment by jmtd** [comment]
Late to reply, but the reason I went with _ for the vcs labels (if memory serves) is it tab-completes, which is a nice-to-have.
