### ISSUE TITLE
`authoritative_source_url` and `authoritative_source`

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/ContainerApplicationGenericLabels#49]
Are those the same thing? Or is one an url (of registry's fronted) and the other registry URI to use with pull?

**Comment by rhatdan** [comment]
I think there should probably only be the _url one.  PTAL @aweiteka @riekrh

**Comment by aweiteka** [comment]
The end-user doing a `docker inspect` should know what this means without documentation. If it's not clear that would suggest consolidating into one. @riekrh ?

**Comment by ghost** [comment]
the _url would contain information redundant with other fields, wouldn't it?

On Thu, Sep 17, 2015 at 8:55 AM, Aaron Weitekamp notifications@github.com
wrote:

> The end-user doing a docker inspect should know what this means without
> documentation. If it's not clear that would suggest consolidating into one.
> @riekrh https://github.com/riekrh ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/projectatomic/ContainerApplicationGenericLabels/issues/49#issuecomment-141072923
> .

## 

Daniel Riek riek@redhat.com
- Sr. Director Systems Design & Engineering
- Red Hat Inc, Tel. +1-617-863-6776

**Comment by twaugh** [comment]
Any update on this?
