### ISSUE TITLE
Use cases for container configuration?

### ISSUE THREAD

**Issue by philips** [projectatomic/ContainerApplicationGenericLabels#7]
There are two examples of using these labels for container configuration? I sort of get the use case for the min memory label but max memory doesn't seem like a realistic concern.

Can whoever wrote the container configuration section explain a few more use cases of what this might be used for?

Also, why are the container that it is formatted as a reverse DNS oid even though these labels are presumably scoped to a single image?

**Comment by philips** [comment]
I guess I should just send a PR to remove it? :)

**Comment by rhatdan** [comment]
I forgot who asked to have those added.  I would guess the max could somehow be used to set a cgroup constraint.  But I think these should not be even covered since they are namespaced and we really are talking about non namespaced labels here.
