### ISSUE TITLE
maintainer instruction is deprecated as of docker engine 1.13

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/ContainerApplicationGenericLabels#78]
We should introduce a substitution for MAINTAINER instruction:

https://github.com/docker/docker/pull/25466

What would it be? `maintainer`, `contact`, `upstream`?

**Comment by aweiteka** [comment]
I think `maintainer` makes the most sense given the history. It would be an optional attribute since it's most relevant for single-developer container images, preferring `vendor` to identify container images from a software company.

**Comment by TomasTomecek** [comment]
@aweiteka agreed. Shall I open a PR?

**Comment by aweiteka** [comment]
Yes, that would be great. Thanks.
