### ISSUE TITLE
label capitalization style?

### ISSUE THREAD

**Issue by philips** [projectatomic/ContainerApplicationGenericLabels#8]
In each section the label capitalization is different, between all caps, CamelCase and lower case. I would suggest that we just standardize on lowercase as it is common for things like urls, programming language variable names, etc.

**Comment by rhatdan** [comment]
Just getting back from Vacation.  

Sure makes sense.  We have apps that have use the UPPERCASE labels for RUN, INSTALL, UNINSTALL, I can change my tooling to use both and we can change the docs to use the lower case names.  The others aren't really used yet.

**Comment by philips** [comment]
Sounds good, filed the PR in #11

**Comment by larsks** [comment]
I was going to suggest that capitalization should not be semantically important, but just making everything lowercase works too.  :+1:

**Comment by rhatdan** [comment]
I have changed our atomic tool to handle lowercase, Uppercase and Capitlized.  I think we probably want to enforce this as case insensitive.  We definitely do not want

Run
RUN
run 

To mean different things.

**Comment by rhatdan** [comment]
Changed to lowercase with underscores.
